### ISSUE TITLE
Grammarly breaks all ContentEditable elements

### ISSUE THREAD

**Issue by richardwei6** [AHSAppDevTeam/Aces#8]
With the Grammarly extension enabled, clicking on the boxes makes them black and unselectable. 

You can see that Grammarly underlines the text but I'm unable to interact with the text in any way. See attached screenshots:

![Title textbox](https://i.imgur.com/OMffwtm.png)
![Author textbox](https://i.imgur.com/StQ0IMc.png)
![Article Body textbox](https://i.imgur.com/E3UoO7v.png)

**Comment by xingyzt** [comment]
Could you switch to light mode and see if the text is visible and/or interactive?

**Comment by richardwei6** [comment]
Nope the same thing happens on light mode

![Title & Author textbox](https://i.imgur.com/CSgCuZ5.png)
![Article Body textbox](https://i.imgur.com/KEkAE9Y.png)

**Comment by xingyzt** [comment]
Does grammarly show up on the searchbar or is it limited to the text boxes in the editor?

**Comment by richardwei6** [comment]
Search box is completely fine, it just seems to be the text boxes in the editor

**Comment by xingyzt** [comment]
Replace all contenteditable element with textarea inputs. Should be fixed.
